import assert from 'node:assert/strict';
import { app, BrowserWindow } from 'electron';
import { EventEmitter } from 'node:events';
import { mkdtempSync, rmSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { TimerService } from '../src/assistant/timer';
import { TimerRepository } from '../src/storage/timer-repository';
import { ReminderService } from '../src/assistant/reminders';
import { ScheduleRepository } from '../src/storage/schedule-repository';
import { FollowupService } from '../src/assistant/followup';
import { FollowupRepository } from '../src/storage/followup-repository';
import { PanelController } from '../src/assistant/panel-controller';
import { BabyLifeRepository } from '../src/storage/baby-life-repository';
import { LifecycleRepository } from '../src/storage/lifecycle-repository';
import { loadOrCreateEgg } from '../src/storage/pet-repository';
import { hatchScenes } from '../src/pet/lifecycle';
import { createPetWindow, refreshBabyPresentation } from '../src/main/windows';
import { createPromptWindows } from '../src/main/prompt-window';
import { createResultCardWindow } from '../src/main/result-card-window';
import { timerNotifications } from '../src/main/notifications';
const directory=mkdtempSync(path.join(tmpdir(),'jarvis-v02-screen-'));
app.setPath('userData',directory);app.on('window-all-closed',()=>{});
app.on('quit',()=>{try{rmSync(directory,{recursive:true,force:true,maxRetries:3,retryDelay:100});}catch{console.warn('fixture retained');}});
const timeout=setTimeout(()=>app.exit(2),45000);
const pause=(ms=60)=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(check:()=>Promise<boolean>) {for(let i=0;i<100;i++){if(await check())return;await pause(20);}throw new Error('UI_TIMEOUT');}
app.whenReady().then(async()=>{
  app.dock?.hide();
  const lifecycle=new LifecycleRepository(directory,{namePolicy:{trim:true,maxCodePoints:20},developmentTrigger:true});
  let saved=lifecycle.apply(0,{type:'prepare'});
  for(const scene of hatchScenes)saved=lifecycle.apply(saved.revision,{type:'witness',scene});
  lifecycle.apply(saved.revision,{type:'name',name:'통합시험'});
  let now=Date.now();let stage:'egg'|'baby'='egg';
  const baby=new BabyLifeRepository(directory,()=>now);const identity=loadOrCreateEgg(directory);
  const pet=await createPetWindow(identity,true,()=>{},()=>({...identity,name:'통합시험'}),baby);
  pet.webContents.setBackgroundThrottling(false);
  const card=await createResultCardWindow(pet);let panels:Awaited<ReturnType<typeof createPromptWindows>>;
  let joined:PanelController;let refreshing=false;
  const refresh=()=>{if(!joined||!panels||refreshing)return;refreshing=true;try{joined.sync();baby.setAttention(joined.attention());refreshBabyPresentation(pet);panels.refresh();card.refresh(stage==='baby'&&joined.state().card!==null);}finally{refreshing=false;}};
  class Notice extends EventEmitter{show(){this.emit('show');}close(){this.emit('close');}}
  const native:Notice[]=[];
  const notifier=timerNotifications(undefined,{backend:{isSupported:()=>true,create:()=>{const n=new Notice();native.push(n);return n;}},onClick:item=>{if(item)joined.acknowledge({kind:'timer',id:item.id},0);}});
  const timers=new TimerService(new TimerRepository(directory),{wall:()=>now,monotonic:()=>now},notifier.notify,refresh);
  const schedules=new ReminderService(new ScheduleRepository(directory),()=>now,(_row,report)=>report('shown'),refresh);
  const followups=new FollowupService(new FollowupRepository(directory),()=>now,refresh);
  joined=new PanelController(timers,schedules,followups,()=>stage,refresh,async()=>({ok:false,message:'실제 휴지통 검사는 하지 않습니다.'}),()=>now);
  panels=await createPromptWindows(timers,true,schedules,()=>null,{card:card.win,cardPage:card.page,api:{read:async()=>joined.state(),action:a=>joined.action(a),submitTimer:async(id,text,mode,replace)=>joined.submitTimer(id,text,mode,replace),snack:()=>joined.snack()}});
  const run=(source:string)=>panels.prompt.webContents.executeJavaScript(source);
  const crun=(source:string)=>card.win.webContents.executeJavaScript(source);
  panels.prompt.webContents.setBackgroundThrottling(false);card.win.webContents.setBackgroundThrottling(false);
  panels.open();await until(()=>run("document.activeElement.id==='request'"));
  assert.equal(await run("document.querySelector('#baby-examples').hidden"),true);
  await run(`(()=>{const i=document.querySelector('#request');i.value='라면 3분 30초 타이머';i.dispatchEvent(new CompositionEvent('compositionstart'));i.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true,cancelable:true}));i.dispatchEvent(new CompositionEvent('compositionend'));})()`);
  await until(async()=>timers.views().length===1);assert.equal(timers.views()[0].title,'라면');assert.equal(timers.views()[0].durationMs,210000);
  await pause(150);assert.equal(timers.views().length,1,'IME commit must submit exactly once');
  stage='baby';refresh();await until(()=>run("!document.querySelector('#baby-examples').hidden"));
  const short=timers.create('short',1000,{title:'확인할 일',menu:'hidden'});assert.equal(short.ok,true);
  now+=1000;timers.tick();refresh();await pause();
  assert.equal(card.win.isVisible(),false,'no simultaneous app popup');assert.equal(panels.notice.isVisible(),false);
  native[native.length-1].emit('click');await until(()=>crun("document.querySelector('#card-title').textContent==='확인할 일'"));
  assert.equal(await crun("document.querySelector('#card-title').textContent"),'확인할 일');
  await pause(150);
  mkdirSync(path.resolve('.local/v02-integration/screens'),{recursive:true});
  writeFileSync(path.resolve('.local/v02-integration/screens/card.png'),(await card.win.webContents.capturePage()).toPNG());
  await crun("document.querySelector('#later').click();document.querySelector('[data-minutes=\"5\"]').click()");
  await until(async()=>joined.attention().level===1);refresh();
  assert.equal(card.win.isVisible(),false);assert.equal(joined.attention().holdLife,true);
  now+=300000;timers.tick();assert.equal(followups.tick().length,1);refresh();
  await until(()=>crun("document.body.dataset.round==='1'"));
  await crun("document.querySelector('#later').click();document.querySelector('[data-minutes=\"5\"]').click()");
  await until(async()=>joined.attention().level===2);assert.equal(joined.attention().intervalSeconds,60);
  await joined.action({type:'ack',kind:'timer',id:'short'});refresh();await pause();
  await crun("document.querySelector('#done').click()");await until(()=>crun("!document.querySelector('#undo').hidden"));
  await crun("document.querySelector('#undo').click()");await until(async()=>joined.attention().level===2);
  const foreign=new BrowserWindow({show:false,webPreferences:{preload:path.join(__dirname,'../src/preload/prompt.js'),sandbox:true,contextIsolation:true,nodeIntegration:false}});
  await foreign.loadFile(path.join(__dirname,'../src/renderer/prompt.html'));
  assert.equal(await foreign.webContents.executeJavaScript("window.assistantPanel.action({type:'cancel',kind:'timer',id:'short'}).then(()=>false,()=>true)"),true);
  assert.equal(await crun("window.assistantPanel.submitTimer('forbidden','1초 타이머','default').then(()=>false,()=>true)"),true);foreign.destroy();
  await joined.action({type:'cancel',kind:'timer',id:'short'});refresh();
  await run("document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}))");
  await until(async()=>!panels.prompt.isVisible());
  panels.open();await pause(150);
  const output=path.resolve('.local/v02-integration/screens');mkdirSync(output,{recursive:true});
  writeFileSync(path.join(output,'input.png'),(await panels.prompt.webContents.capturePage()).toPNG());
  writeFileSync(path.join(output,'baby.png'),(await pet.webContents.capturePage()).toPNG());
  console.log('PASS: integrated IME submit once, stage help, native-click card, weak/strong reminder, done/undo, sender restrictions, Escape, no initial popup');
  notifier.dispose();panels.dispose();card.dispose();pet.destroy();timers.dispose();schedules.dispose();followups.dispose();baby.close();lifecycle.close();
  clearTimeout(timeout);app.quit();
}).catch(error=>{console.error(error);clearTimeout(timeout);app.exit(1);});
